services:
  app:
    image: 'api-users'
    build:
      context: .
      dockerfile: users.dockerfile
    container_name: api-users
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://34.31.251.210:5432/users-jobpay
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080