services:
  app:
    image: 'api-users'
    build:
      context: .
      dockerfile: users.dockerfile
    container_name: api-users
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users-jobpay
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-users"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbusers:/data/postgres-users
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  dbusers:
    external: true